In [1]:
import array
a=array.array('i',[1,2,3,4,5,6])
for i in range (0,6):
    ab=array.array('l',[6,9,3,78,5,2,6,])
    for l in range (0,7):
        print(ab[l])
    print(a[i])

    

6
9
3
78
5
2
6
1
6
9
3
78
5
2
6
2
6
9
3
78
5
2
6
3
6
9
3
78
5
2
6
4
6
9
3
78
5
2
6
5
6
9
3
78
5
2
6
6


In [2]:
import array
arr=array.array('i',[1,2,3,4,5,6])
arr.append(50)
print(arr)

#sort
arr12=array.array('i',sorted(arr))
print(arr12)

newarr=arr.tolist()
print(newarr)

array('i', [1, 2, 3, 4, 5, 6, 50])
array('i', [1, 2, 3, 4, 5, 6, 50])
[1, 2, 3, 4, 5, 6, 50]


In [4]:
import numpy as np
arr1=np.array([[1,4,4],[4,3,8]])

print(arr1.shape)


(2, 3)


In [5]:
import numpy as np
ar2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar2.shape)

(3, 3)


In [6]:
a1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a1.reshape(6,2))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [7]:
a2=np.array([[2,3,4],[5,3,7]])
print(a2.ndim)

2


In [8]:
a3=np.array([2,4,7,5,3,6,9,5,3,9])
print(a3.dtype)

int64


In [9]:
a4=np.array([2,3,4,7,2,6,8,7,9])
print(a4.size)

9


In [10]:
a5=np.array([[2,3,4,5],[6,7,8,9]])
print(a5[1][2])
print(a5)

8
[[2 3 4 5]
 [6 7 8 9]]


In [11]:
a6=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(a6[1][1])
print("-----------")
print(a6)
print("*********")
print(a6[0:1])
print("*********")
print(a6[:,1])
print("*********")

7
-----------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
*********
[[1 2 3 4 5]]
*********
[ 2  7 12]
*********


In [12]:
b=np.array([1,2,3])

print(b+2)
print(b*2)

[3 4 5]
[2 4 6]


In [13]:
b1=np.array([2,4,6,8])
print(np.sum(b1))
print(np.mean(b1))
print(np.median(b1))
print(np.max(b1))
print(np.min(b1))

20
5.0
5.0
8
2


In [14]:
b2=np.array([7,2,7,9,3,7,4,2,6,9,2,6])
print(np.median(b2))



6.0


In [15]:
a = np.array([1,2,3,4,5,6])
b = a.reshape([2,3])

print(b)
print(a.flatten())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [18]:
a=np.array([1,5,4,6,8,9,2,1,4,6,8,7])
print(np.arange(0,12))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [22]:
a = np.array([3,2,6,8,8,3,5,9])

print(np.linspace(0,1,3))
print(np.ones(len(a)))

[0.  0.5 1. ]
[1. 1. 1. 1. 1. 1. 1. 1.]


In [23]:
a = np.array([[2,3,4,5,6],[3,5,7,1,5]])
print(np.sum(a))
print(np.sum(a,axis=1))

41
[20 21]


In [24]:
np.ones(3)

array([1., 1., 1.])

In [25]:
np.zeros(4)

array([0., 0., 0., 0.])

In [27]:
a1 = np.array([[2,4,3], [7,3,8]])
print(a1.shape)

b1 = np.array([[9,8,3,4], [7,2,9,1], [9,2,3,7]])
print(b1.shape)

print(np.dot(a1, b1))

(2, 3)
(3, 4)
[[ 73  30  51  33]
 [156  78  72  87]]


In [28]:
np.random.random([3,4])

array([[0.15517266, 0.39008347, 0.31587087, 0.38907485],
       [0.33565188, 0.30148619, 0.06819611, 0.44440646],
       [0.25850307, 0.92099943, 0.79712988, 0.01668845]])

In [30]:
import numpy as np

rng = np.random.default_rng()
rng.integers(6, size=(3,5))

array([[0, 2, 4, 5, 2],
       [0, 0, 3, 5, 5],
       [5, 3, 5, 1, 0]])

In [32]:
a1 = np.array([[2,5,7,1], [8,3,6,4]])
b1 = np.array([[1,4,2,9], [5,7,3,8]])
add = np.add(a1, b1)
print(add)
sub = np.subtract(a1, b1)
print(sub)
scalar = 3 * a1
print(scalar)

[[ 3  9  9 10]
 [13 10  9 12]]
[[ 1  1  5 -8]
 [ 3 -4  3 -4]]
[[ 6 15 21  3]
 [24  9 18 12]]
